--CAU 1
CREATE DATABASE Qlvattu
GO

USE Qlvattu
GO

CREATE TABLE VATU(
	MaVT VARCHAR(10) PRIMARY KEY,
	TenVT NVARCHAR(10),
	Donvi VARCHAR(10),
	Dongia INT
)
GO

CREATE TABLE HOADON(
	MaHD VARCHAR(10) PRIMARY KEY,
	MaVT VARCHAR(10),
	Soluong INT,
	Thanhtien FLOAT
)
GO

INSERT INTO VATU
	VALUES ('VT1',N'Sắt','KG',50000),
			('VT2',N'Thép','KG',450000),
			('VT3',N'Cát','KG',20000),
			('VT4',N'Xi măng','KG',19000)
GO

INSERT INTO HOADON
	VALUES ('HD1','VT1',50,NULL),
			('VT2',N'Thép',45,NULL),
			('VT3',N'Cát',90,NULL),
			('VT4',N'Xi măng',100,NULL)
GO

SELECT * FROM VATU
SELECT * FROM HOADON

ALTER TABLE VATU
	ADD Ghichu NVARCHAR(20)

--CAU 2
CREATE DATABASE QLNV
GO

USE QLNV
GO

CREATE TABLE NV(
	MaNV VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(20),
	MaCQ VARCHAR(10),
	PhongBan NVARCHAR(20),
	Lương FLOAT
)
GO

CREATE TABLE CQ(
	MaCQ VARCHAR(10) PRIMARY KEY,
	TenCQ NVARCHAR(20),
	Diachi NVARCHAR(20)
)
GO

INSERT INTO NV
	VALUES ('MS50',N'Hữu Đạt','CQ50','Phòng IT',2000000),
			('MS51',N'Quang Đạt','CQ51','Phòng IT',1000000)
GO


INSERT INTO CQ
	VALUES ('CQ50',N'Bảo hiểm AB','Lĩnh Nam'),
			('CQ51',N'Bảo hiểm ABC','Nam Du'),
			('CQ52',N'Bảo hiểm ABCD','Du Nam')
GO

SELECT CQ.* FROM CQ
	WHERE NOT EXISTS(
	SELECT 1 FROM NV
	WHERE NV.MaCQ=CQ.MaCQ
)

SELECT MaNV,COUNT(HoTen) AS SoTen FROM NV
	GROUP BY MaNV
	HAVING COUNT(HoTen) >= 1
	ORDER BY SoTen DESC

SELECT * FROM NV
JOIN CQ ON CQ.MaCQ = NV.MaCQ
WHERE CQ.TenCQ = N'Bảo hiểm AB'

SELECT * FROM NV
SELECT * FROM CQ
GO

SELECT * FROM NV
	WHERE MaCQ = 'CQ50'
GO

SELECT NV.* FROM NV
	JOIN  CQ ON NV.MaCQ = CQ.MaCQ
	WHERE CQ.TenCQ = N'Bảo hiểm AB'
GO

SELECT CQ.* FROM CQ
	LEFT JOIN NV ON CQ.MaCQ = NV.MaCQ
	WHERE NV.MaCQ IS NULL
GO

SELECT * FROM NV
	ORDER BY Lương ASC
GO

CREATE VIEW Thongtin AS
	SELECT MaNV,Hoten,MaCQ,PhongBan,Lương FROM NV
GO

SELECT * FROM Thongtin 
GO 



