CREATE USER QTMANG FOR LOGIN QTLOGIN
DROP USER QTMANG

GRANT LOL ON JJ TO HOSHINA
	WITH GRANT OPTION 

USE BANHANG
GO
GRANT SELECT ON R TO QUANTRIMANG

REVOKE ON FROM -- XOA QUYEN NGUOI DUNG